name: Aya formal verification

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  aya:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Run Aya checks
        run: scripts/run_aya.sh
